version: "3"
services:
  postgres:
    image: postgres
    container_name: rifa_db_postgres
    restart: always
    environment:
      POSTGRES_DB: rifa_db
      POSTGRES_USER: rifa_user
      POSTGRES_PASSWORD: rifa_dev_pass
    volumes:
      - "rifa_vol:/var/lib/postgresql/data"
    networks:
      - rifa_net
    ports:
      - 5434:5432
networks:
  rifa_net:
volumes:
  rifa_vol: